* Draft
** Page One
*** Panel One
TITLE: Straw, Coal, & Bean

*** Panel Two
Close-up of fish head on tile.

UNSEEN COMMENTER: Is it Awake?
COMMENTER 2: Hard to tell when they don't blink.

*** Panel Three
Long Shot of fish sitting upright, taking inhale from gas mask.

UNSEEN COMMENTER: Oh, look who's up.
COMMENTER 2: Just in time for the soup.

*** Panel Four
Two birds walk in distance across platform in background. Close up of fish standing with two figures in far distance yelling to him.

FIGURE ONE: Bean!
FISH: Fish.
FIGURE ONE: What?
FISH: I'm a fish, not a bean.
FIGURE ONE: Bean... Fish... Whatever...

*** Panel Five
Medium Shot. Straw and Coal crowd together to speak to Bean, who is taking a hit of Gas. Coal is smoking a cigarette.

STRAW: He's Coal. I'm Straw.
COAL: Where are you going, Bean?
BEAN: I'm escaping- away from the Cook and the Soup.

*** Panel Six
Medium Shot. Closer than previous panel - just Coal and Bean in frame.

COAL: We're fleeing as well. Let's go together.

*** Panel Seven
Medium Shot. Straw is back in frame.

STRAW: We'll form a merry band.
BEAN: Ummm... sure...
COAL: You don't sound enthusiastic.
BEAN: It's just --

*** Panel Eight
Medium Shot. Bean stands center frame with back to camera. Straw stands on the left and Coal on the right.

BEAN: I'm a fish.
COAL: You mentioned it.
BEAN: [points to Straw] He's a broom.
STRAW: Not quite.
BEAN: [points to Coal] And you're a cat --
COAL: Nope.
BEAN: A rock.
COAL: How dare you. I am Coal...

*** Panel Nine
Straw stands on left, talking to Bean who stands on the right.
